--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: bggdb-svc 
  namespace: bggns
spec: 
  #mysql://root:kYnyNNZXnGxcDnCmWflDnNPyePIQwxGk@
  #:36000/railway
  type: ExternalName
  externalName: tramway.proxy.rlwy.net